### ISSUE TITLE
fix error Storage Account Name already existing (bicep)

### ISSUE THREAD

**Issue by chrey-gh** [Azure/mlops-project-template#2]
when running the bicep cicd pipeline we often encounter the errormessage , that the storage account name is already in use. This is because storage accounts need to be unique across Azure. Therefore we create a uniquefying function for the storage account name in bicep script

**Comment by chrey-gh** [comment]
added uniqueString to storage account name creation.

**Comment by cindyweng** [comment]
fixed with latest release
