### ISSUE TITLE
(classic) Batch online training pipeline

### ISSUE THREAD

**Issue by chrey-gh** [Azure/mlops-project-template#31]
Batch on line training pipeline fails in step Test-Deployment. Error:
/home/vsts/.local/bin/az account set --subscription 96e7c4cd-67ef-4e02-b10b-4fd99b1a6b34
/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1654821379124.sh

Uploading taxi-batch.csv (< 1 MB): 0.00B [00:00, ?B/s]
Uploading taxi-batch.csv (< 1 MB): 100%|██████████| 134k/134k [00:00<00:00, 816kB/s]
Uploading taxi-batch.csv (< 1 MB): 100%|██████████| 134k/134k [00:00<00:00, 813kB/s]

ERROR: Met error <class 'Exception'>:upstream request timeout
Please check log in debug mode for more details.

**Comment by cindyweng** [comment]
I believe this is fixed.
