### ISSUE TITLE
Bug : error in the path 

### ISSUE THREAD

**Issue by samelhousseini** [Azure/mlops-project-template#99]
https://github.com/Azure/mlops-project-template/blob/9cf02e5ffc3b6576bc5a425ec6ba28cc9c80ecc7/classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml#L10

Should be:
    - template: ../../config-infra-dev.yml

**Comment by setuc** [comment]
Resolved
